### PR TITLE
Implement support for unsubscribing from a subscription

### PR DESCRIPTION
**Pull request by darrenclark**
Implements support for letting clients unsubscribe from a subscription via a `stop` message.

---

Two of the changes:

- Added support for a `handle_info` function inside `MessageHandler`s, much like `GenServer`'s `handle_info` (24c192b)
- Added support for callback when `DataBroker.init` is called (9f664b7)

are implemented so that a `MessageHandler` can be notified when a `DataBroker` is started.

d698fa0 glues things together by changing `AbsintheMessageHandler` to:
- keep a keyword list of *operation id* -> *`DataBroker` `pid`*
- handle `stop` messages by stopping `DataBroker`s associated with a given *operation id*
- `DataBroker.terminate` handles calling `Absinthe.Subscription.unsubscribe/2`

---

All feedback is definitely welcome!  Not really sure if I approached this in an idiomatic Elixir way, or if there is a simpler approach

### CODE REVIEW

**Comment by darrenclark** [comment]
@easco Thanks for the feedback! This is perfect, exactly what I was looking for.

Re: 24c192b, handling general messages was meant to allow the `MessageHandler` to get a message from the `DataBroker`'s process so that the MessageHandler could track it & stop it when needed.

But, it's definitely not relevant anymore if we have a process that manages data brokers.  And it sounds like having a separate process will also make things a lot cleaner.

Were you thinking it might look something like (ignoring naming / missing parameters):

```elixir
defmodule DataBrokerWatcher do
  use GenServer

  def start_broker(apollo_socket, operation_id) do
    # ...
  end

  def stop_broker(apollo_socket, operation_id) do
    # ...
  end

  #  ... rest of implementation that tracks the brokers ...
end
```

And then `AbsintheMessageHandler` would call these to start & stop data brokers?

If you want, I can take a stab at refactoring it too

**Comment by easco** [comment]
If you would like to take a stab at it here's what I was thinking.  You would have your broker watcher and the functions you have are fine, except that they would need an extra argument (the watcher itself).  So:

    def start_broker(watcher, apollo_socket, operation_id) do
        …

This should probably be in its own subsystem so you might want a supervision tree:

```
                   +--------------+
                   |              |
                   |  Supervisor  |
                   |              |
                   +------+-------+
                          |
                          |
       +------------------+---------------+
       |                                  |
+------+--+                    +----------+---------+
|         |                    |                    |
| Broker  |                    | Dynamic Supervisor |
| Watcher |                    |                    |
|         |                    +--------------------+
+---------+

```

And then the actual brokers would become children of the dynamic supervisor.

**Comment by darrenclark** [comment]
Cool, I'll give it a go!

**Comment by darrenclark** [comment]
I pushed some changes.  It still needs some cleanup, but it seems to work (and I think it's a huge improvement)

Basic gist of it is:

nonode_nohost_png


Thoughts?

**Comment by easco** [comment]
Why is the Broker Registry a separate process from the Data Broker Watcher?  (this is **not** a criticism but a straightforward question).

Processes are units of concurrency or of fault-tolerance isolation. I can't imagine that concurrency would be a good reason for running them in separate processes... perhaps fault tolerance... should these two things be able to fail independently.  Hmmm...

Seems like the Broker Registry could easily be an ETS table and the Broker Watcher simply a module (not a Process) that makes use of that Registry.  Does the watcher maintain state of its own? (I guess I could go read the code... being lazy on Friday).

**Comment by darrenclark** [comment]
@easco I had initially started down the path of expecting the Broker Watcher would need to store the socket/operation_id <-> mapping itself (hence it being a process), but then I stumbled upon the `Registry` module that handled storing the mappings for me.

Like you said, I think it might make sense to make the `DataBrokerWatcher` just a module that had `start` and `stop` functions? something like:

```elixir
def start(socket, operation_id, supervisor, registry)
def stop(socket, operation_id, supervisor, registry)
```

Or perhaps I just put those `start` / `stop` functions in `DataBroker` itself?

**Pull request closed without merging**
